export {default as Header} from './Navbar'
export {default as Footer} from './Footer'
export {default as Slider} from './Slider'
export {default as Accordion} from './Accordion'
export {default as Card} from './Card/Card'
export {default as Loader} from './Loader/Loader'